name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Guardar Videos y Screenshots
        uses: actions/upload-artifact@v4
        if: always() # Esto hace que se guarden aunque el test falle
        with:
          name: reportes-visuales
          path: |
            cypress/screenshots
            cypress/videos